services:
  mongo:
    image: "memphisos/mongo:4.2"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
  memphis-cluster:
    image: "memphisos/memphis-broker:0.4.0"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "9000:9000"
      - "6666:6666"
    environment:
      - ROOT_PASSWORD=memphis
      - CONNECTION_TOKEN=memphis
      - DOCKER_ENV=true
      - LOGS_RETENTION_IN_DAYS=3
      - ANALYTICS=true
      - JWT_SECRET=35nhvjfosfklgmfg56+fdsgzvfnjksacvbhfksfkgofadsjfgjkoldsdkfvpl’jbgio;dfsjgkl;’XZFVMifobd;dlgjv[sfvjmiodfkvs2fh;fhk44gfdhksdkfdffk
      - REFRESH_JWT_SECRET=35c7b3eb969db065bfa3c66b38e4323e8f73113f3965dfb55c6bc585dcb0ba62bd399e2588fdc8f709ae0b63fb24be32590f134506ca1d7a4314339f11b8045a
    command: >
      -js --auth=memphis
networks:
  memphis:
    ipam:
      driver: default